"""The derived queue: causes ranked by tier, never a weighted scalar."""
import json

import fidelity_queue as Q


def _row(name, **kw):
    r = {"file": name, "status": "measured", "melody": 0.9, "aud": 0.8, "gate": 0.7}
    r.update(kw)
    return r


def test_slug_is_stable_and_kebab():
    assert Q.slug("Refusal", "aud vs approved", "ACE_II") == "refusal-aud-vs-approved-ace-ii"
    assert Q.slug("Refusal", "aud vs approved", "ACE_II") == Q.slug("Refusal", "aud vs approved", "ACE_II")


def test_stale_approvals_are_tier_1_and_user_tagged():
    appr = {"ACE_II": {"status": "stale", "failed": ["aud_vs_approved"],
                       "listener_should_check": "aud_vs_approved", "evidence": {"aud_vs_approved": 0.7}}}
    (e,) = Q.stale_approvals(appr)
    assert e["tier"] == 1 and e["tag"] == "[user]" and e["files"] == ["ACE_II"]
    assert "aud_vs_approved" in e["verify"]


def test_length_failures_are_tier_2():
    rows = [_row("A.sid", length_delta=7.5, length_bounded=False),
            _row("B.sid", length_delta=1.0, length_bounded=False),
            _row("C.sid", length_delta=12.0, length_bounded=True)]
    got = Q.length_failures(rows)
    assert [e["files"] for e in got] == [["A"], ["C"]]
    assert all(e["tier"] == 2 and e["tag"] == "[main]" for e in got)


def test_refusals_carry_their_margin():
    refs = [{"song": "X.sid", "combination": "two_stage", "criterion": "aud_vs_orig",
             "value": 0.80, "bound": 0.81}]
    (e,) = Q.refusal_entries(refs)
    assert e["tier"] == 3 and e["evidence"]["margin"] == -0.01 and e["files"] == ["X"]


def test_census_buckets_group_by_cause_across_files():
    rows = [_row("A.sid", onset_census=[{"kind": "phase", "effect": 0x01}, {"kind": "match"}]),
            _row("B.sid", onset_census=[{"kind": "phase", "effect": 0x01}]),
            _row("C.sid", onset_census=[{"kind": "flat", "effect": 0x80}])]
    got = Q.census_buckets(rows)
    top = got[0]
    assert top["tier"] == 5 and sorted(top["files"]) == ["A", "B"]
    assert top["cause"].startswith("onset phase")
    assert len(got) == 4        # two causes x (subagent confirm, main fix)


def test_column_outliers_use_the_corpus_spread():
    rows = [_row(f"F{i}.sid", gate=0.7) for i in range(10)] + [_row("Bad.sid", gate=0.1)]
    got = Q.column_outliers(rows)
    assert [e["files"] for e in got] == [["Bad"]]
    assert got[0]["tier"] == 6 and "gate" in got[0]["cause"]


def test_entries_are_ordered_by_tier_then_files_reached():
    e1 = {"id": "a", "tier": 5, "files": ["A"]}
    e2 = {"id": "b", "tier": 5, "files": ["A", "B", "C"]}
    e3 = {"id": "c", "tier": 2, "files": ["Z"]}
    assert [e["id"] for e in Q.ordered([e1, e2, e3])] == ["c", "b", "a"]


def test_annotate_marks_tracked_and_refuted_without_dropping():
    entries = [{"id": "x", "files": ["Commando"], "cause": "column pitch outlier", "tier": 6}]
    plan = {"tasks": [{"id": "commando-voice-1-plays-g-sharp-7", "source": "", "title": "",
                       "verify": "Commando voice 1 ... pitch ..."}]}
    runs = {"some-run": {"outcome": "done", "evidence": "Commando ... origin shift refuted ... pitch"}}
    Q.annotate(entries, plan, runs)
    assert entries[0]["already_tracked"] == "commando-voice-1-plays-g-sharp-7"
    assert entries[0]["already_refuted"] == "some-run"
    assert len(entries) == 1


def test_first_and_last_seen_persist_and_closed_are_reported():
    prior = {"entries": [{"id": "old", "first_seen": "0.5.440", "last_seen": "0.5.446"},
                         {"id": "keep", "first_seen": "0.5.441", "last_seen": "0.5.446"}]}
    entries = [{"id": "keep"}, {"id": "new"}]
    Q.carry_seen(entries, prior, "0.5.447")
    assert entries[0]["first_seen"] == "0.5.441" and entries[0]["last_seen"] == "0.5.447"
    assert entries[1]["first_seen"] == "0.5.447"
    assert [c["id"] for c in Q.closed_since(prior, entries)] == ["old"]


def test_render_has_one_table_per_tier_and_a_provenance_line():
    entries = [{"id": "a", "tier": 2, "source": "length", "cause": "runs long", "files": ["A"],
                "tag": "[main]", "evidence": {"length_delta": 7.5}, "verify": "ends within 5 s",
                "first_seen": "0.5.447", "last_seen": "0.5.447",
                "already_tracked": None, "already_refuted": None}]
    text = Q.render(entries, [], {"version": "0.5.447", "head": "abc1234", "seconds": 60})
    assert "Generated by `python/fidelity_queue.py` (h2g 0.5.447, abc1234)" in text
    assert "## Tier 2" in text and "| `a` |" in text
