"""Every option convert() takes must be reachable from a preset.

This defect has shipped twice. `--slides` was emitted but never forwarded
(AUDIT.md's first verified defect), and `--filter` arrived in v0.5.72 wired
into convert() and README but into neither `presets.py`'s `always` block nor
`fidelity._preset_opts` -- so every measurement ran with the filter off and the
next artefact regeneration would have recorded the feature as doing nothing.

Both were the same cause: the option list is maintained by hand in more than
one place. `_preset_opts` now derives it from `inspect.signature(convert)`;
these tests fail if a new option escapes either the derivation or the block.
"""
import inspect
import json
from pathlib import Path

import pytest

from fidelity import (_NOT_CONVERT_OPTS, _PER_SONG_OPTS, _RENAMED_OPTS,
                      _convert_options, _preset_opts)
from h2g import __version__
from h2g.convert import convert
from presets import EXCLUDED_FROM_ALWAYS

PRESETS = Path(__file__).resolve().parents[2] / "presets.json"


def _always():
    """The shipped block, but only when it was generated by this version.

    presets.json is regenerated after a conversion-changing commit, not during
    one, so between the two it legitimately predates the options it should
    carry. Asserting against a stale artefact would fail for the one reason
    this test is not about.
    """
    if not PRESETS.exists():
        pytest.skip("presets.json not generated")
    doc = json.loads(PRESETS.read_text(encoding="utf-8"))
    if __version__ not in str(doc.get("generator", "")):
        pytest.skip(f"presets.json predates h2g {__version__} -- regenerate it")
    return doc.get("always", {})


def test_convert_options_are_exactly_its_keywords_minus_the_inputs():
    params = set(inspect.signature(convert).parameters)
    assert params - {"sid_path", "log"} == set(_convert_options())


def test_every_convert_option_is_produced_by_preset_opts():
    """The guard the two shipped defects needed."""
    doc = {"always": {}, "songs": {}}
    produced = set(_preset_opts(doc, "any.sid"))
    for opt in _convert_options():
        assert opt in produced, (
            f"convert() takes {opt!r} and _preset_opts never passes it, so a "
            f"preset run silently converts without it")


def test_preset_opts_forwards_what_the_always_block_sets():
    doc = {"always": {o: True for o in _convert_options()}, "songs": {}}
    doc["always"]["format"] = "gts5"
    doc["always"]["tempo"] = "auto"
    opts = _preset_opts(doc, "any.sid")
    for opt in _convert_options():
        if opt in _PER_SONG_OPTS or opt in ("fmt", "tempo"):
            continue
        assert opts[opt] is True, f"{opt} was set in `always` and not forwarded"


def test_preset_opts_is_accepted_by_convert_verbatim():
    """Nothing in the dict may be a keyword convert() would reject."""
    doc = {"always": {}, "songs": {}}
    params = set(inspect.signature(convert).parameters)
    assert set(_preset_opts(doc, "any.sid")) <= params


def test_the_shipped_always_block_carries_every_gated_option():
    """A gated option left out of `always` is a feature that measures as dead.

    Only options that are a no-op where their routine is absent belong here;
    the packing ones are excluded by name because convert() does not take them.
    """
    always = _always()
    for opt in _convert_options():
        if (opt in _PER_SONG_OPTS or opt in _NOT_CONVERT_OPTS
                or opt in EXCLUDED_FROM_ALWAYS):
            continue
        key = _RENAMED_OPTS.get(opt, opt)
        assert key in always, (
            f"{key!r} is a convert() option missing from presets.json's "
            f"`always` block -- regenerate presets.json, or add it to "
            f"presets.EXCLUDED_FROM_ALWAYS with the reason")


def test_every_deliberate_exclusion_is_a_real_option():
    """A stale name in the exclusion set would hide a genuinely missing one."""
    assert EXCLUDED_FROM_ALWAYS <= set(_convert_options())
