"""Every option convert() takes must be reachable from a preset.

This defect has shipped twice. `--slides` was emitted but never forwarded
(AUDIT.md's first verified defect), and `--filter` arrived in v0.5.72 wired
into convert() and README but into neither `presets.py`'s `always` block nor
`fidelity._preset_opts` -- so every measurement ran with the filter off and the
next artefact regeneration would have recorded the feature as doing nothing.

Both were the same cause: the option list is maintained by hand in more than
one place. `_preset_opts` now derives it from `inspect.signature(convert)`;
these tests fail if a new option escapes either the derivation or the block.
"""
import inspect
import json
from pathlib import Path

import pytest

from fidelity import (_NOT_CONVERT_OPTS, _PER_SONG_OPTS, _RENAMED_OPTS,
                      _convert_options, _preset_opts)
from h2g import __version__
from h2g.convert import convert
import presets
from presets import EXCLUDED_FROM_ALWAYS

PRESETS = Path(__file__).resolve().parents[2] / "presets.json"


def _always():
    """The shipped block, but only when it was generated by this version.

    presets.json is regenerated after a conversion-changing commit, not during
    one, so between the two it legitimately predates the options it should
    carry. Asserting against a stale artefact would fail for the one reason
    this test is not about.
    """
    if not PRESETS.exists():
        pytest.skip("presets.json not generated")
    doc = json.loads(PRESETS.read_text(encoding="utf-8"))
    if __version__ not in str(doc.get("generator", "")):
        pytest.skip(f"presets.json predates h2g {__version__} -- regenerate it")
    return doc.get("always", {})


def test_convert_options_are_exactly_its_keywords_minus_the_inputs():
    params = set(inspect.signature(convert).parameters)
    assert params - {"sid_path", "log"} == set(_convert_options())


def test_every_convert_option_is_produced_by_preset_opts():
    """The guard the two shipped defects needed."""
    doc = {"always": {}, "songs": {}}
    produced = set(_preset_opts(doc, "any.sid"))
    for opt in _convert_options():
        assert opt in produced, (
            f"convert() takes {opt!r} and _preset_opts never passes it, so a "
            f"preset run silently converts without it")


def test_preset_opts_forwards_what_the_always_block_sets():
    doc = {"always": {o: True for o in _convert_options()}, "songs": {}}
    doc["always"]["format"] = "gts5"
    doc["always"]["tempo"] = "auto"
    opts = _preset_opts(doc, "any.sid")
    for opt in _convert_options():
        if opt in _PER_SONG_OPTS or opt in ("fmt", "tempo"):
            continue
        assert opts[opt] is True, f"{opt} was set in `always` and not forwarded"


def test_preset_opts_is_accepted_by_convert_verbatim():
    """Nothing in the dict may be a keyword convert() would reject."""
    doc = {"always": {}, "songs": {}}
    params = set(inspect.signature(convert).parameters)
    assert set(_preset_opts(doc, "any.sid")) <= params


def test_the_shipped_always_block_carries_every_gated_option():
    """A gated option left out of `always` is a feature that measures as dead.

    Only options that are a no-op where their routine is absent belong here;
    the packing ones are excluded by name because convert() does not take them.
    """
    always = _always()
    for opt in _convert_options():
        if (opt in _PER_SONG_OPTS or opt in _NOT_CONVERT_OPTS
                or opt in EXCLUDED_FROM_ALWAYS):
            continue
        key = _RENAMED_OPTS.get(opt, opt)
        assert key in always, (
            f"{key!r} is a convert() option missing from presets.json's "
            f"`always` block -- regenerate presets.json, or add it to "
            f"presets.EXCLUDED_FROM_ALWAYS with the reason")


def test_every_deliberate_exclusion_is_a_real_option():
    """A stale name in the exclusion set would hide a genuinely missing one."""
    assert EXCLUDED_FROM_ALWAYS <= set(_convert_options())


# --- per-song options ------------------------------------------------------
#
# An option can be right for a few files and wrong corpus-wide, which `always`
# cannot express. `presets.py --fidelity` records those per song, and until
# v0.5.177 nothing read them: `_preset_opts` consulted `always` alone, so a
# searched setting would have been written and then ignored -- the exact shape
# in which --slides and --filter each shipped dead.

def test_a_song_entry_beats_the_always_block_in_both_directions():
    doc = {"always": {"no_test_restart": False, "pulse": True},
           "songs": {"a.sid": {"no_test_restart": True, "pulse": False}}}
    got = _preset_opts(doc, "a.sid")
    assert got["no_test_restart"] is True, "a per-song override was ignored"
    assert got["pulse"] is False, "a per-song False must switch one off too"
    other = _preset_opts(doc, "b.sid")
    assert (other["no_test_restart"], other["pulse"]) == (False, True)


def test_the_fidelity_searched_options_are_kept_out_of_always():
    """They are per song by construction: each is a corpus-wide loss and a win
    on a handful of files, so an `always` entry would be wrong either way."""
    assert set(presets.FIDELITY_TOGGLES) <= EXCLUDED_FROM_ALWAYS
    assert not set(presets.FIDELITY_TOGGLES) & set(presets.FIXED)
    assert set(presets.FIDELITY_TOGGLES) <= set(_convert_options())


def test_the_fidelity_search_cannot_be_won_by_deleting_notes():
    """Section 7.eee: the candidate this search exists for reached `wave` 99.5%
    on Commando by losing 79 notes, because a per-frame agreement rewards losing
    the events it scores. Melody alone would not catch it either -- it collapses
    consecutive repeats, so a re-struck note lost is invisible to it."""
    ref = (0.80, 0.75, 600, (0, 0, 0x3800, 0x3800))
    assert presets.fidelity_better((0.90, 0.80, 600, (0, 0, 0x3800, 0x3800)), ref)
    # better melody, but the sequence or the notes went with it
    assert not presets.fidelity_better((0.90, 0.70, 600, (0, 0, 0x3800, 0x3800)), ref)
    assert not presets.fidelity_better((0.90, 0.80, 599, (0, 0, 0x3800, 0x3800)), ref)


def test_a_gain_inside_the_noise_is_not_recorded():
    ref = (0.80, 0.75, 600, (0, 0, 0x3800, 0x3800))
    assert not presets.fidelity_better((0.80 + presets.FIDELITY_MARGIN / 2,
                                        0.90, 900, (0, 0, 0, 0)), ref)
    assert presets.fidelity_better((0.80 + presets.FIDELITY_MARGIN,
                                   0.75, 600, (0, 0, 0, 0)), ref)


def test_restoring_noise_the_original_has_and_we_have_none_of_is_a_win():
    """The second way to win, and the one --two-stage needs. A conversion with
    no noise at all where the original has some is missing its drums outright
    (Trans-Atlantic: 0 frames against 1089), which no agreement percentage can
    say because there is nothing on our side to disagree with. Scoring it on
    `wave` would reject it -- restoring a 1-4 frame transient moves that column
    the wrong way even when the transient is right."""
    ref = (0.80, 0.75, 600, (0, 1089, 0x3800, 0x3800))
    assert presets.fidelity_better((0.80, 0.75, 600, (928, 1089, 0x3800, 0x3800)), ref)
    # ...but not if the notes go with it
    assert not presets.fidelity_better((0.80, 0.75, 599, (928, 1089, 0x3800, 0x3800)), ref)
    # and not where the original has no noise either: that is invention
    assert not presets.fidelity_better((0.80, 0.75, 600, (928, 0, 0x3800, 0x3800)),
                                       (0.80, 0.75, 600, (0, 0, 0x3800, 0x3800)))
    # nor where we already sound some -- the criterion is "none at all"
    assert not presets.fidelity_better((0.80, 0.75, 600, (999, 1089, 0x3800, 0x3800)),
                                       (0.80, 0.75, 600, (900, 1089, 0x3800, 0x3800)))


def test_restored_noise_has_to_be_audible():
    """The SID's noise is an LFSR clocked by the frequency register, so a noise
    frame at a low frequency makes no sound at all. Counting frames rather than
    sound selected four files whose restored drums a listener could not hear:
    the attack in this dialect carries a pitch as well as a waveform, and only
    the waveform is read, so the noise plays at the note's own $05xx."""
    ref = (0.80, 0.75, 600, (0, 1089, 0, 0x3800))
    assert presets.fidelity_better((0.80, 0.75, 600, (928, 1089, 0x3000, 0x3800)), ref)
    assert not presets.fidelity_better((0.80, 0.75, 600, (928, 1089, 0x05CE, 0x3800)), ref)


def test_restored_noise_has_to_land_closer_than_none_at_all():
    """|ours - theirs| < |0 - theirs|, not merely "more than zero". Without the
    upper bound the criterion took Sigma Seven, whose two-stage attack sounds 82
    noise frames where the original sounds 41 -- drums invented at twice the
    rate are not an improvement on drums missing."""
    ref = (0.80, 0.75, 600, (0, 41, 0x3800, 0x3800))
    assert presets.fidelity_better((0.80, 0.75, 600, (40, 41, 0x3800, 0x3800)), ref)
    assert not presets.fidelity_better((0.80, 0.75, 600, (82, 41, 0x3800, 0x3800)), ref)
    assert not presets.fidelity_better((0.80, 0.75, 600, (83, 41, 0x3800, 0x3800)), ref)
